export const theme = {
  breakpoints: {
    base: '0px',
    sm: '414px',
    md: '744px',
    lg: '1080px',
    xl: '1280px',
    '2xl': '1440px',
    xxl: '1440px',
  },
  colors: {
    'accent-default': '#FFFFFF',
    'accent-hover': '#F9F9F9',
    'accent-pressed': '#F2F2F2',
    'accent-disabled': '#DDDDDD',
    'accent-focus': '#C2C2FF',
    'primary-default': '#4F4FFF',
    'primary-hover': '#6565FF',
    'primary-pressed': '#2323FF',
    'primary-disabled': '#D2D2F0',
    'primary-focus': '#C2C2FF',
    'secondary-default': '#1D3853',
    'secondary-hover': '#334D68',
    'secondary-pressed': '#122334',
    'secondary-disabled': '#959DA6',
    'secondary-focus': '#C2C2FF',
    'alert-error-default': '#DB3B21',
    'alert-error-hover': '#F14A2F',
    'alert-error-pressed': '#C31B00',
    'alert-error-disabled': '#EDC3C3',
    'alert-error-focus': '#C2C2FF',
    'alert-warning-default': '#FC9403',
    'alert-warning-hover': '#FFA932',
    'alert-warning-pressed': '#E88700',
    'alert-warning-disabled': '#E3AD61',
    'alert-success-default': '#1AAA55',
    'alert-success-hover': '#1CC661',
    'alert-success-pressed': '#168845',
    'alert-success-disabled': '#CEE2D6',
    'alert-inform-default': '#1F78D1',
    'alert-inform-hover': '#2793FF',
    'alert-inform-pressed': '#1861AB',
    'alert-inform-disabled': '#8CB0D3',
    'background-light': '#FFFFFF',
    'background-dark': '#000000',
    'background-card': '#FCFCFF',
    'background-page': '#0C0C0C',
    'background-overlay': '#BCBCD7',
    'background-static': '#D5D5EB',
    'background-container-default': '#FFFFFF',
    'background-container-hover': '#FDFDFD',
    'background-container-pressed': '#E0E0E0',
    'background-container-disabled': '#EAEAEA',
    'background-container-active': '#D5D5EB',
    'background-action-default': '#FDFDFF',
    'background-action-hover': '#F5F5FF',
    'background-action-pressed': '#E4E4E4',
    'background-action-disabled': '#EAEAEA',
    'background-action-active': '#D5D5EB',
    'background-error': '#FFDDD8',
    'background-warning': '#FFE5C1',
    'background-success': '#DEFFEC',
    'background-inform': '#E4F2FF',
    'text-light': '#FFFFFF',
    'text-primary': '#222222',
    'text-secondary': '#888888',
    'text-disabled': '#BDC4CC',
    'text-button-accent': '#4F4FFF',
    'text-button-primary': '#FFFFFF',
    'text-button-secondary': '#FFFFFF',
    'text-button-alert': '#FFFFFF',
    'text-badge-solid': '#FFFFFF',
    'text-badge-outline': '#4F4FFF',
    'text-badge-subtle': '#4F4FFF',
    'text-link-accent-default': '#EF8A13',
    'text-link-accent-hover': '#FFAD4C',
    'text-link-accent-pressed': '#FF8A00',
    'text-link-primary-default': '#4F4FFF',
    'text-link-primary-hover': '#6565FF',
    'text-link-primary-pressed': '#2323FF',
    'text-link-secondary-default': '#1D3853',
    'text-link-secondary-hover': '#334D68',
    'text-link-secondary-pressed': '#122334',
    'text-success': '#15793E',
    'text-warning': '#CB7600',
    'text-error': '#A72D1A',
    'ui-element-divider': '#202020',
    'ui-element-outline-default': '#E7E7E7',
    'ui-element-outline-active': '#D7DBE7',
    'ui-element-outline-disabled': '#F2F2F2',
  },
  space: {
    'spacer-px': '0.0625rem',
    'spacer-half': '0.125rem',
    'spacer-1': '0.25rem',
    'spacer-2': '0.5rem',
    'spacer-3': '0.75rem',
    'spacer-4': '1rem',
    'spacer-5': '1.25rem',
    'spacer-6': '1.5rem',
    'spacer-7': '1.75rem',
    'spacer-8': '2rem',
    'spacer-9': '2.25rem',
    'spacer-10': '2.5rem',
    'spacer-12': '3rem',
    'spacer-14': '3.5rem',
    'spacer-16': '4rem',
    'spacer-20': '5rem',
    'spacer-24': '6rem',
    'spacer-28': '7rem',
    'spacer-32': '8rem',
    'spacer-36': '9rem',
    'spacer-40': '10rem',
    'spacer-44': '11rem',
    'spacer-48': '12.25rem',
    'spacer-52': '13rem',
    'spacer-56': '14rem',
    'spacer-60': '15rem',
    'spacer-64': '16rem',
    'spacer-72': '18rem',
    'spacer-80': '20rem',
    'spacer-86': '24rem',
    'spacer-0': '0rem',
  },
  radii: {
    'radii-half': '0.125rem',
    'radii-1': '0.25rem',
    'radii-2': '0.375rem',
    'radii-3': '0.5rem',
    'radii-4': '0.75rem',
    'radii-5': '1rem',
    'radii-6': '1.5rem',
    'radii-card': '0.5rem',
    'radii-modal': '0.5rem',
    'radii-alertdialog': '0.5rem',
    'radii-popover': '0.5rem',
  },
  shadows: {
    'elevation-default': '0px 1px 2px 0px rgba(0, 0, 0, 0.06), 0px 1px 3px 0px rgba(0, 0, 0, 0.1)',
    'elevation-interactive': '0px 4px 6px -1px rgba(0, 0, 0, 0.1), 0px 2px 4px -1px rgba(0, 0, 0, 0.06)',
    'elevation-modals': '0px 10px 15px -3px rgba(0, 0, 0, 0.1), 0px 4px 6px -2px rgba(0, 0, 0, 0.05)',
    'elevation-outline': '0px 0px 0px 3px rgba(194, 194, 255, 0.3)',
    'elevation-inner': 'inset 0px 2px 4px 0px rgba(0, 0, 0, 0.06)',
  },
  textStyles: {
    'text-header-4XL': {
      color: 'text-primary',
      fontSize: ['2.875rem', null, null, '4.5rem'],
      fontWeight: ['bold', null, null, 'bold'],
      letterSpacing: ['-0.0625rem', null, null, '-0.0625rem'],
      lineHeight: ['3.25rem', null, null, '5.25rem'],
      textDecoration: ['none', null, null, 'none'],
    },
    'text-header-3XL': {
      color: 'text-primary',
      fontSize: ['2.625rem', null, null, '4rem'],
      fontWeight: ['bold', null, null, 'bold'],
      letterSpacing: ['-0.0625rem', null, null, '-0.0625rem'],
      lineHeight: ['3rem', null, null, '4.625rem'],
      textDecoration: ['none', null, null, 'none'],
    },
    'text-header-2XL': {
      color: 'text-primary',
      fontSize: ['2.25rem', null, null, '2.75rem'],
      fontWeight: ['semibold', null, null, 'semibold'],
      letterSpacing: ['-0.0625rem', null, null, '0rem'],
      lineHeight: ['2.625rem', null, null, '3.25rem'],
      textDecoration: ['none', null, null, 'none'],
    },
    'text-header-XL': {
      color: 'text-primary',
      fontSize: ['1.5rem', null, null, '2.25rem'],
      fontWeight: ['semibold', null, null, 'semibold'],
      letterSpacing: ['-0.0625rem', null, null, '-0.0625rem'],
      lineHeight: ['2rem', null, null, '2.75rem'],
      textDecoration: ['none', null, null, 'none'],
    },
    'text-header-L': {
      color: 'text-primary',
      fontSize: ['1.5rem', null, null, '1.5rem'],
      fontWeight: ['bold', null, null, 'semibold'],
      letterSpacing: ['0rem', null, null, '0rem'],
      lineHeight: ['2rem', null, null, '2.25rem'],
      textDecoration: ['none', null, null, 'none'],
    },
    'text-header-M': {
      color: 'text-primary',
      fontSize: ['1.25rem', null, null, '1.25rem'],
      fontWeight: ['semibold', null, null, 'semibold'],
      letterSpacing: ['0rem', null, null, '0rem'],
      lineHeight: ['2rem', null, null, '1.5rem'],
      textDecoration: ['none', null, null, 'none'],
    },
    'text-header-S': {
      color: 'text-primary',
      fontSize: ['1rem', null, null, '1rem'],
      fontWeight: ['bold', null, null, 'semibold'],
      letterSpacing: ['0rem', null, null, '0rem'],
      lineHeight: ['1.25rem', null, null, '1.25rem'],
      textDecoration: ['none', null, null, 'none'],
    },
    'text-header-XS': {
      color: 'text-primary',
      fontSize: ['0.875rem', null, null, '0.875rem'],
      fontWeight: ['bold', null, null, 'semibold'],
      letterSpacing: ['0rem', null, null, '0rem'],
      lineHeight: ['1.25rem', null, null, '1.125rem'],
      textDecoration: ['none', null, null, 'none'],
    },
    'text-body-display-2XL': {
      color: 'text-primary',
      fontSize: ['3.75rem'],
      fontWeight: ['regular'],
      letterSpacing: ['0rem'],
      lineHeight: ['4.5rem'],
      textDecoration: ['none'],
    },
    'text-body-display-XL': {
      color: 'text-primary',
      fontSize: ['3rem'],
      fontWeight: ['regular'],
      letterSpacing: ['0rem'],
      lineHeight: ['3.5rem'],
      textDecoration: ['none'],
    },
    'text-body-display-L': {
      color: 'text-primary',
      fontSize: ['2.25rem'],
      fontWeight: ['regular'],
      letterSpacing: ['0rem'],
      lineHeight: ['2.75rem'],
      textDecoration: ['none'],
    },
    'text-body-display-M': {
      color: 'text-primary',
      fontSize: ['1.875rem'],
      fontWeight: ['regular'],
      letterSpacing: ['0rem'],
      lineHeight: ['2.25rem'],
      textDecoration: ['none'],
    },
    'text-body-display-S': {
      color: 'text-primary',
      fontSize: ['1.25rem'],
      fontWeight: ['regular'],
      letterSpacing: ['0rem'],
      lineHeight: ['1.875rem'],
      textDecoration: ['none'],
    },
    'text-body-display-XS': {
      color: 'text-primary',
      fontSize: ['1.25rem'],
      fontWeight: ['regular'],
      letterSpacing: ['0rem'],
      lineHeight: ['1.875rem'],
      textDecoration: ['none'],
    },
    'text-body-large-regular': {
      color: 'text-primary',
      fontSize: ['1.125rem'],
      fontWeight: ['regular'],
      letterSpacing: ['0.0625rem'],
      lineHeight: ['1.75rem'],
      textDecoration: ['none'],
    },
    'text-body-large-medium': {
      color: 'text-primary',
      fontSize: ['1.25rem'],
      fontWeight: ['semi bold'],
      letterSpacing: ['0rem'],
      lineHeight: ['1.125rem'],
      textDecoration: ['none'],
    },
    'text-body-large-bold': {
      color: 'text-primary',
      fontSize: ['1.25rem'],
      fontWeight: ['bold'],
      letterSpacing: ['0rem'],
      lineHeight: ['1.125rem'],
      textDecoration: ['none'],
    },
    'text-body-regular': {
      color: 'text-primary',
      fontSize: ['1.125rem'],
      fontWeight: ['regular'],
      letterSpacing: ['0rem'],
      lineHeight: ['1.75rem'],
      textDecoration: ['none'],
    },
    'text-body-medium': {
      color: 'text-primary',
      fontSize: ['1rem'],
      fontWeight: ['medium'],
      letterSpacing: ['0rem'],
      lineHeight: ['1.5rem'],
      textDecoration: ['none'],
    },
    'text-body-bold': {
      color: 'text-primary',
      fontSize: ['1.125rem'],
      fontWeight: ['bold'],
      letterSpacing: ['0rem'],
      lineHeight: ['1.75rem'],
      textDecoration: ['none'],
    },
    'text-body-meta-regular': {
      color: 'text-primary',
      fontSize: ['1rem'],
      fontWeight: ['regular'],
      letterSpacing: ['0rem'],
      lineHeight: ['1.375rem'],
      textDecoration: ['none'],
    },
    'text-body-meta-medium': {
      color: 'text-primary',
      fontSize: ['1rem'],
      fontWeight: ['semi bold'],
      letterSpacing: ['0rem'],
      lineHeight: ['1.375rem'],
      textDecoration: ['none'],
    },
    'text-body-meta-bold': {
      color: 'text-primary',
      fontSize: ['0.875rem'],
      fontWeight: ['bold'],
      letterSpacing: ['0rem'],
      lineHeight: ['1.25rem'],
      textDecoration: ['none'],
    },
    'text-body-floating-label-regular': {
      color: 'text-primary',
      fontSize: ['0.75rem'],
      fontWeight: ['regular'],
      letterSpacing: ['0rem'],
      lineHeight: ['1.125rem'],
      textDecoration: ['none'],
    },
    'text-body-floating-label-medium': {
      color: 'text-primary',
      fontSize: ['0.75rem'],
      fontWeight: ['medium'],
      letterSpacing: ['0.15625rem'],
      lineHeight: ['1rem'],
      textDecoration: ['none'],
    },
    'text-body-floating-label-bold': {
      color: 'text-primary',
      fontSize: ['0.75rem'],
      fontWeight: ['bold'],
      letterSpacing: ['0.3125rem'],
      lineHeight: ['1rem'],
      textDecoration: ['none'],
    },
    'text-link-body-large': {
      color: 'text-link-accent-default',
      fontSize: ['1.75rem'],
      fontWeight: ['regular'],
      letterSpacing: ['0rem'],
      lineHeight: ['2.25rem'],
      textDecoration: ['underline'],
    },
    'text-link-body-medium': {
      color: 'text-link-accent-default',
      fontSize: ['1.25rem'],
      fontWeight: ['regular'],
      letterSpacing: ['0rem'],
      lineHeight: ['1.5rem'],
      textDecoration: ['underline'],
    },
    'text-link-body-small': {
      color: 'text-link-accent-default',
      fontSize: ['0.875rem'],
      fontWeight: ['regular'],
      letterSpacing: ['0rem'],
      lineHeight: ['1.75rem'],
      textDecoration: ['underline'],
    },
  },
  components: {
    TextPairing: {
      parts: ['label', 'subLabel'],
      variants: {
        'textpairing-body-display-2XL': {
          label: { variant: 'text-body-display-2XL' },
          subLabel: { variant: 'text-body-large-regular' },
          columnGap: { sm: '1rem', md: '1rem' },
        },
        'textpairing-body-display-XL': {
          label: { variant: 'text-body-display-XL' },
          subLabel: { variant: 'text-body-large-regular' },
          columnGap: { sm: '0.75rem', md: '0.75rem' },
        },
        'textpairing-body-display-L': {
          label: { variant: 'text-body-display-L' },
          subLabel: { variant: 'text-body-large-regular' },
          columnGap: { sm: '0.75rem', md: '0.75rem' },
        },
        'textpairing-body-display-M': {
          label: { variant: 'text-body-display-M' },
          subLabel: { variant: 'text-body-regular' },
          columnGap: { sm: '0.5rem', md: '0.5rem' },
        },
        'textpairing-body-display-S': {
          label: { variant: 'text-body-display-S' },
          subLabel: { variant: 'text-body-regular' },
          columnGap: { sm: '0.5rem', md: '0.5rem' },
        },
        'textpairing-header-4XL': {
          label: { variant: 'text-header-4XL' },
          subLabel: { variant: 'text-body-display-S' },
          columnGap: { md: '1rem', sm: '1.25rem' },
        },
        'textpairing-header-3XL': {
          label: { variant: 'text-header-3XL' },
          subLabel: { variant: 'text-body-display-S' },
          columnGap: { md: '1rem', sm: '1rem' },
        },
        'textpairing-header-2XL': {
          label: { variant: 'text-header-2XL' },
          subLabel: { variant: 'text-body-display-S' },
          columnGap: { md: '1rem', sm: '0.75rem' },
        },
        'textpairing-header-M': {
          label: { variant: 'text-header-M' },
          subLabel: { variant: 'text-body-regular' },
          columnGap: { md: '0.25rem', sm: '0.25rem' },
        },
        'textpairing-header-L': {
          label: { variant: 'text-header-L' },
          subLabel: { variant: 'text-body-regular' },
          columnGap: { md: '0.5rem', sm: '0.25rem' },
        },
        'textpairing-header-XL': {
          label: { variant: 'text-header-XL' },
          subLabel: { variant: 'text-body-large-regular' },
          columnGap: { md: '0.5rem', sm: '0.5rem' },
        },
        'textpairing-body-bold': {
          label: { variant: 'text-body-bold' },
          subLabel: { variant: 'text-body-regular' },
          columnGap: { sm: '0.25rem', md: '0.25rem' },
        },
        'textpairing-body-bold-meta': {
          label: { variant: 'text-body-bold' },
          subLabel: { variant: 'text-body-meta-regular' },
          columnGap: { sm: '0.25rem', md: '0.25rem' },
        },
        'textpairing-body-meta-bold': {
          label: { variant: 'text-body-meta-bold' },
          subLabel: { variant: 'text-body-meta-regular' },
          columnGap: { sm: '0.125rem', md: '0.125rem' },
        },
        'textpairing-body-medium': {
          label: { variant: 'text-body-medium' },
          subLabel: { variant: 'text-body-regular' },
          columnGap: { sm: '0.25rem', md: '0.25rem' },
        },
        'textpairing-body-regular': {
          label: { variant: 'text-body-regular' },
          subLabel: { variant: 'text-body-meta-regular' },
          columnGap: { sm: '0.25rem', md: '0.25rem' },
        },
        'textpairing-body-medium-meta': {
          label: { variant: 'text-body-medium' },
          subLabel: { variant: 'text-body-meta-regular' },
          columnGap: { sm: '0.25rem', md: '0.25rem' },
        },
        'textpairing-body-meta-medium': {
          label: { variant: 'text-body-meta-medium' },
          subLabel: { variant: 'text-body-meta-regular' },
          columnGap: { sm: '0.125rem', md: '0.125rem' },
        },
        'textpairing-body-meta-regular': {
          label: { variant: 'text-body-meta-regular' },
          subLabel: { variant: 'text-body-meta-regular' },
          columnGap: { sm: '0.125rem', md: '0.125rem' },
        },
      },
    },
  },
};
